apiVersion: v1
kind: PersistentVolume
metadata:
   name: prometheus-pv-claim
spec:
   storageClassName: manual
   capacity:
     storage: 5Gi
   accessModes:
     - ReadWriteOnce
   hostPath:
     path: "/mnt/data"

